name: Build Image
on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.build-image.outputs.output1 }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.write-output.outputs.image }}
    permissions:
      contents: 'read'
      packages: 'write'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker Metadata action
        uses: docker/metadata-action@v4.6.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      
      - name: Write job's output
        id: write-output
        run: echo "image=${{ steps.meta.outputs.tags }}" >> "$GITHUB_OUTPUT"
