name: Build code
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      # - name: Run golint
      #   uses: golangci/golangci-lint-action@v3.6.0

      - name: Run tests
        run: go test -race -vet=off `go list ./... | grep -v test | grep -v vendor`