name: Development CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-code:
    uses: TranTheTuan/orchestrator/.github/workflows/build_code.yaml@dev

  build-image:
    if: github.event_name == 'push'
    uses: TranTheTuan/orchestrator/.github/workflows/build_image.yaml@dev
    needs: [build-code]
    with:
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      registry: ${{ env.REGISTRY }}

  deploy-app:
    if: github.event_name == 'push' 
    uses: TranTheTuan/orchestrator/.github/workflows/update_image.yaml@master
    with:
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
