name: Go package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-code:
    uses: ./.github/workflows/build_code.yaml

  build-image:
    if: github.event_name == 'push'
    uses: ./.github/workflows/build_image.yaml
    needs: [build-code]

  deploy:
    if: github.event_name == 'push'
    uses: TranTheTuan/orchestrator/.github/workflows/update_image.yaml@master
    with:
      image: ${{ needs.build-image.outputs.image }}
    secrets:
      envPAT: ${{ secrets.PAT }}
    needs: [build-image]
