name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Build
        run: go build -v ./...

      - name: Run golint
        uses: golangci/golangci-lint-action@v3.6.0

      - name: Run tests
        run: go test -race -vet=off `go list ./... | grep -v test | grep -v vendor`
