name: CICD workflows
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest]
    steps:
      - name: Run Echo
        run: echo "works"


